#!/bin/bash
for nt in 32 64 ; do
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=float -DNB=$nb -DCLOCK -DNT=${nt}
 ./a.out; rm ./a.out
done
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=double -DNB=$nb -DCLOCK -DNT=$nt
 ./a.out; rm ./a.out
done
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=float -DTWOF -DNB=$nb -DCLOCK -DNT=$nt
 ./a.out; rm ./a.out
done
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=double -DTWOF -DNB=$nb -DCLOCK -DNT=$nt
 ./a.out; rm ./a.out
done
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=float -DTWOF -DMORE_PREC -DNB=$nb -DCLOCK -DNT=$nt
 ./a.out; rm ./a.out
done
for nb in 1 4 16 32 64 ; do
 /usr/local/cuda/bin/nvcc -gencode arch=compute_75,code=sm_75 -O3 --expt-relaxed-constexpr -std=c++17 clockMatrix.cu -DFLOAT=double -DTWOF -DMORE_PREC -DNB=$nb -DCLOCK -DNT=$nt
 ./a.out; rm ./a.out
done
done
