#!/bin/bash

lscpu
rocm-smi
echo  " "

# export MPFR_DIR=/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/gcc/9.3.0/lib
for f in acos acosh asin asinh atan atanh cbrt cos cosh erf erfc exp exp10 exp2 expm1 j0 j1 log log10 log1p log2 sin sinh sqrt tan tanh y0 y1 lgamma tgamma; do
   /opt/rocm/hip/bin/hipcc -O3 check_exhaustive-555.hip.cpp -lmpfr -lgmp -lm -fopenmp -march=native -DSTR=$f
   // nvcc -DSTR=$f check_exhaustive-555.cu --cudart shared -gencode arch=compute_$CCAP,code=sm_$CCAP -O3 -std=c++17 --compiler-options="-O3 -L$MPFR_DIR -lmpfr -lgmp -lm -fopenmp"
   echo "checking " $f
   time ./a.out
done

#egrep "checking|Total|wrong" fullCheck.log  | sed 's/checking/Q/g' | sed 's/^.*x=/x=/g' |  tr '\n' ' ' | tr 'Q' '\n'
#egrep "checking|Total" fullCheck.log  | sed 's/checking/Q/g' |  tr '\n' ' ' | tr 'Q' '\n' | sed 's/=/ /g' | cut -f 3,6,9,11 -d' '
#egrep "checking|Total" fullCheck.log  | sed 's/checking/Q/g' |  tr '\n' ' ' | tr 'Q' '\n' | sed 's/=/ /g' | cut -f 3,6,9,11 -d' ' | sed 's/ / \& /g' | sed 's/$/ \\\\/g'
#egrep "checking|Total|wrong" fullCheckAll.log  | sed 's/checking/Q/g' | sed 's/^.*x=/x=/g' |  tr '\n' ' ' | tr 'Q' '\n' | tr '=' ' ' | sed 's/x /x=/g' | awk '{print $1,"&", $5,"&", $8,"&", $10, "\\\\ %",  $2 }' | sort
