#!/bin/bash
for f in acos acosh asin asinh atan atanh cbrt cos cosh erf erfc exp exp10 exp2 expm1 j0 j1 log log10 log1p log2 sin sinh sqrt tan tanh y0 y1 gamma lgamma tgamma; do
   nvcc -DSTR=$f check_exhaustive.cu --cudart shared -gencode arch=compute_70,code=sm_70 -O3 -std=c++17 --compiler-options="-O3 -lmpfr -lgmp -lm -fopenmp"
   echo "checking " $f
   ./a.out
done

