#!/bin/bash

lscpu
nvidia-smi
echo  " "

export CCAP=80
export MPFR_DIR=/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/gcc/9.3.0/lib
for f in acos acosh asin asinh atan atanh cbrt cos cosh erf erfc exp exp10 exp2 expm1 j0 j1 log log10 log1p log2 sin sinh sqrt tan tanh y0 y1 lgamma tgamma; do
   c++ -DFOO=$f -DUSE_DOUBLE -O3 check_sample.cc -lmpfr -lgmp -lm -fopenmp
   echo "checking " $f
   time ./a.out -v -threshold 20000 -seed 41008
done
